# Generated by Django 3.0 on 2020-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200624_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='password',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
